# PoC Figure Reprocessing Pipeline Parameters
# Use with: tw launch --params-file params.yaml

# Input/Output
# NOTE: Upload samplesheets to S3 first, then update this path
input: "s3://motleybio/Laboratory/SINGLE_V_TRINITY_COMPARISONS/samplesheets/all_ready_samples.csv"
outdir: "s3://motleybio/Laboratory/SINGLE_V_TRINITY_COMPARISONS"

# Reference genome (S3 paths)
genome_fasta: "s3://motleybio/Resources/reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa"
genome_fai: "s3://motleybio/Resources/reference_genome/GRCh38_full_analysis_set_plus_decoy_hla.fa.fai"
annotation_gtf: "s3://motleybio/Resources/GTF/Homo_sapiens.GRCh38.112.chr_label.gtf"

# Pre-built indices
biscuit_index: "s3://motleybio/Resources/biscuit_reference_genome/"
star_index: "s3://motleybio/Resources/Star_Genome/"

# Optional: intergenic BED for CNV filtering
# intergenic_bed: "s3://motleybio/Resources/bed_masks/intergenic.bed"
